### ISSUE TITLE
Remove path from dependencies

### ISSUE THREAD

**Issue by jgraef** [nimiq/core-rs-albatross#30]
Instead of specifying our dependencies like this

```toml
nimiq-database = { path = "../database", version = "0.1" }
```

we can omit the `path` and have a `patch` section in the workspace's `Cargo.toml`:

```toml
[patch.crates-io]
nimiq-database = { path = "../database" }
```
